name: Build/release

on:
  push:

jobs:
  release:
    runs-on: macos-11
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn build:all && ls dist/
        env:
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: dist/*.*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v2
        with:
          name: build-artifact
          path: dist/*.*
